from pathlib import Path
from datetime import datetime
from rich.console import Console

from microfoon.config import OBSIDIAN_VAULT_PATH
from microfoon.database import Recording, ProcessingStatus

console = Console()

class ObsidianExporter:
    def __init__(self):
        if not OBSIDIAN_VAULT_PATH.exists():
            console.log(f"[yellow]Obsidian vault not found at {OBSIDIAN_VAULT_PATH}. Creating directory...[/yellow]")
            OBSIDIAN_VAULT_PATH.mkdir(parents=True, exist_ok=True)
        self.vault_path = OBSIDIAN_VAULT_PATH

    def export(self, recording: Recording) -> Path:
        """Exports a recording to an Obsidian markdown file."""
        safe_title = "".join(c for c in recording.title if c.isalnum() or c in (' ', '-', '_')).strip()
        filename = f"{safe_title}.md"
        file_path = self.vault_path / filename

        content = f"""# {recording.title}

**Date**: {recording.created_at.strftime("%Y-%m-%d %H:%M:%S")}
**Source**: [[{recording.original_filename}]]
**Status**: {recording.status.value}
**Audio File**: `{recording.stored_filename}`

## Note
{recording.summary}

## Transcript
{recording.transcript}

---
*Generated by Microfoon*
"""

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            console.log(f"[green]Exported to Obsidian:[/green] {file_path}")
            return file_path
        except Exception as e:
            console.log(f"[bold red]Export failed:[/bold red] {e}")
            return None
